# The Docker image that will be used to build your app
image: alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r images public/
    - cp  *.html public/
  artifacts:
    paths:
      - public
  only:
    - pages